//! Targeted mutation-killing tests.
//!
//! Each test is annotated with the specific mutant it is designed to kill.
//! Generated by manual mutation analysis of `contract.rs` and `storage.rs`.
//! See `docs/mutation/report.md` for the full methodology.

#![cfg(test)]

use soroban_sdk::{testutils::Address as _, Address};

use crate::{
    contract::{VestingDrips, VestingDripsClient},
    error::VestingError,
    tests::{advance_ledger, setup_env},
};

use super::super::tests::token_helper::{create_token, mint_to};

// ── Helper ────────────────────────────────────────────────────────────────────

fn make_stream(
    rate: i128,
    cliff: u32,
    total: u32,
) -> (
    soroban_sdk::Env,
    Address,
    VestingDripsClient<'static>,
    Address,
    Address,
    Address,
) {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, _) = create_token(&env, &sponsor);
    mint_to(&env, &token, &sponsor, rate * total as i128);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &rate, &cliff, &total)
        .unwrap();
    (env, cid, client, sponsor, recipient, token)
}

// ── M01: `rate <= 0` → `rate < 0` ────────────────────────────────────────────
// A mutant changing `<=` to `<` would allow rate=0 through. Existing test covers
// rate=0. This test ensures rate=-1 is also rejected (covers the `<=` vs `<` swap
// *and* the `< 0` → `<= 0` direction).

#[test]
fn m01_negative_rate_rejected() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, _) = create_token(&env, &sponsor);

    let err = client
        .create_vesting_stream(&sponsor, &recipient, &token, &-1, &50, &200)
        .unwrap_err();
    assert_eq!(err, VestingError::InvalidRate.into());
}

// ── M02: `total_duration <= cliff_duration` → `total_duration < cliff_duration`
// A mutant dropping `=` from `<=` would allow total==cliff through.
// `test_create_stream_invalid_duration_fails` already covers total==cliff,
// but let's make the intent explicit with an assertion on the exact equality boundary.

#[test]
fn m02_total_equals_cliff_duration_rejected() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, _) = create_token(&env, &sponsor);

    // total == cliff: must fail
    let err = client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &100, &100)
        .unwrap_err();
    assert_eq!(err, VestingError::InvalidDuration.into());

    // total == cliff + 1: must succeed
    mint_to(&env, &token, &sponsor, 10);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &0, &1)
        .unwrap();
}

// ── M03: `cancel_stream` — `current_ledger >= cliff_ledger` → `> cliff_ledger`
// A mutant replacing `>=` with `>` would give a full refund even when cancelled
// exactly at the cliff, instead of paying out the earned ledgers.

#[test]
fn m03_cancel_exactly_at_cliff_pays_earned_tokens() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, token_client) = create_token(&env, &sponsor);
    // rate=10, cliff=50, total=200 → deposit=2000; cliff at ledger 150
    mint_to(&env, &token, &sponsor, 2_000);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &50, &200)
        .unwrap();

    // Advance exactly to cliff_ledger (100 + 50 = 150)
    advance_ledger(&env, 50);
    client.cancel_stream(&sponsor, &recipient).unwrap();

    // earned = 50 ledgers × 10 = 500; refund = 150 ledgers × 10 = 1500
    assert_eq!(token_client.balance(&recipient), 500);
    assert_eq!(token_client.balance(&sponsor), 1_500);
}

// ── M04: `cancel_stream` — cancel after end_ledger caps at end_ledger
// Tests that `active_end = current_ledger.min(end_ledger)` in cancel is live.

#[test]
fn m04_cancel_after_end_ledger_caps_at_end() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, token_client) = create_token(&env, &sponsor);
    // rate=10, cliff=50, total=100 → deposit=1000; end at ledger 200
    mint_to(&env, &token, &sponsor, 1_000);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &50, &100)
        .unwrap();

    // Advance well past end_ledger
    advance_ledger(&env, 200);
    client.cancel_stream(&sponsor, &recipient).unwrap();

    // All tokens belong to recipient; nothing left for sponsor.
    assert_eq!(token_client.balance(&recipient), 1_000);
    assert_eq!(token_client.balance(&sponsor), 0);
}

// ── M05: `cancel_stream` — cancel with zero earned (cliff just reached, no prior claims)
// Tests the `recipient_share > 0` guard: when earned=0 (cancel exactly at start
// with cliff=0 edge), no transfer to recipient should occur.

#[test]
fn m05_cancel_at_start_with_cliff_zero_no_recipient_transfer() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, token_client) = create_token(&env, &sponsor);
    // cliff_duration=0 → cliff_ledger == start_ledger; cancel immediately
    mint_to(&env, &token, &sponsor, 100);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &0, &10)
        .unwrap();

    // No ledger advance — current == start == cliff; earned = 0
    client.cancel_stream(&sponsor, &recipient).unwrap();

    // Recipient earned nothing; full deposit back to sponsor.
    assert_eq!(token_client.balance(&recipient), 0);
    assert_eq!(token_client.balance(&sponsor), 100);
}

// ── M06: `claim_vested` — `current_ledger < cliff_ledger` → `<=`
// A `<=` mutant would reject claims made exactly at the cliff.
// `test_first_claim_at_cliff_includes_all_accrued` already covers this;
// this test pins the exact ledger numbers to catch off-by-one regressions.

#[test]
fn m06_claim_at_exact_cliff_ledger_succeeds() {
    let (env, _, client, _, recipient, token) = make_stream(5, 10, 100);
    let token_client =
        soroban_sdk::token::TokenClient::new(&env, &token);

    // cliff_ledger = 100 + 10 = 110; advance exactly 10
    advance_ledger(&env, 10);
    assert_eq!(env.ledger().sequence(), 110); // sanity-check

    let claimed = client.claim_vested(&recipient).unwrap();
    assert_eq!(claimed, 50); // 10 ledgers × 5
    assert_eq!(token_client.balance(&recipient), 50);
}

// ── M07: `claim_vested` — `claimable_amount == 0` → `!= 0`
// This mutant would invert the NothingToClaim guard, always returning
// NothingToClaim on a valid claim. The positive claim tests already cover
// this, but this test explicitly exercises claimable==0 being rejected.

#[test]
fn m07_zero_claimable_amount_returns_nothing_to_claim() {
    let (env, _, client, _, recipient, _) = make_stream(10, 50, 200);

    // Advance to cliff, claim everything accrued so far.
    advance_ledger(&env, 50);
    client.claim_vested(&recipient).unwrap();

    // Do NOT advance. Claimable == 0 → must return NothingToClaim.
    let err = client.claim_vested(&recipient).unwrap_err();
    assert_eq!(err, VestingError::NothingToClaim.into());
}

// ── M08: `claim_vested` — `stream_finished = active_end == end_ledger` → `!=`
// A `!=` mutant removes the schedule mid-stream and never at the real end,
// breaking all subsequent claims. Covered structurally by incremental claim
// tests, but this pins schedule presence at end-1 vs end.

#[test]
fn m08_schedule_removed_only_at_end_ledger() {
    let (env, _, client, _, recipient, _) = make_stream(10, 5, 20);
    // end_ledger = 100 + 20 = 120

    // Claim at cliff (105) — schedule still active
    advance_ledger(&env, 5);
    client.claim_vested(&recipient).unwrap();
    assert!(client.get_schedule(&recipient).is_some());

    // Claim 10 ledgers before end (ledger 110) — schedule still active
    advance_ledger(&env, 5);
    client.claim_vested(&recipient).unwrap();
    assert!(client.get_schedule(&recipient).is_some());

    // Claim exactly at end_ledger — schedule must be removed
    advance_ledger(&env, 10);
    client.claim_vested(&recipient).unwrap();
    assert!(client.get_schedule(&recipient).is_none());
}

// ── M09: `claimable_amount` view — `current_ledger < cliff_ledger` → `<=`
// A `<=` mutant returns 0 exactly at the cliff instead of the accrued amount.

#[test]
fn m09_claimable_amount_view_at_exact_cliff_is_nonzero() {
    let (env, _, client, _, recipient, _) = make_stream(10, 50, 200);

    // Advance exactly to cliff_ledger (150)
    advance_ledger(&env, 50);
    let amount = client.claimable_amount(&recipient);
    assert_eq!(amount, 500); // 50 ledgers × 10
}

// ── M10: `claimable_amount` view — one ledger before cliff returns 0

#[test]
fn m10_claimable_amount_view_one_before_cliff_is_zero() {
    let (env, _, client, _, recipient, _) = make_stream(10, 50, 200);

    // cliff at 150; advance to 149
    advance_ledger(&env, 49);
    assert_eq!(client.claimable_amount(&recipient), 0);
}

// ── M11: `claimable_amount` view — nonexistent schedule returns 0 (not panic)

#[test]
fn m11_claimable_amount_no_schedule_returns_zero() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let nobody = Address::generate(&env);

    assert_eq!(client.claimable_amount(&nobody), 0);
}

// ── M12: `is_cliff_passed` — `>=` → `>` (off-by-one at exact cliff ledger)

#[test]
fn m12_is_cliff_passed_true_at_exact_cliff_ledger() {
    let (env, _, client, _, recipient, _) = make_stream(10, 50, 200);

    // One before cliff: false
    advance_ledger(&env, 49);
    assert!(!client.is_cliff_passed(&recipient));

    // Exactly at cliff: must be true
    advance_ledger(&env, 1);
    assert_eq!(env.ledger().sequence(), 150); // sanity
    assert!(client.is_cliff_passed(&recipient));
}

// ── M13: `is_cliff_passed` — nonexistent schedule returns false (not panic)

#[test]
fn m13_is_cliff_passed_no_schedule_returns_false() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let nobody = Address::generate(&env);

    assert!(!client.is_cliff_passed(&nobody));
}

// ── M14: `cancel_stream` — `earned_ledgers` uses `last_claimed_ledger`, not `start_ledger`
// After a partial claim, cancel should only pay the *unclaimed* earned portion,
// not re-pay from the start.

#[test]
fn m14_cancel_after_partial_claim_uses_last_claimed_ledger() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, token_client) = create_token(&env, &sponsor);
    // rate=10, cliff=50, total=200 → deposit=2000
    mint_to(&env, &token, &sponsor, 2_000);
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &10, &50, &200)
        .unwrap();

    // Claim at cliff (ledger 150) → 500 tokens to recipient
    advance_ledger(&env, 50);
    let claimed = client.claim_vested(&recipient).unwrap();
    assert_eq!(claimed, 500);

    // Cancel 20 ledgers later (ledger 170) → earned since last claim: 20×10=200
    advance_ledger(&env, 20);
    client.cancel_stream(&sponsor, &recipient).unwrap();

    // Recipient: 500 (claim) + 200 (cancel) = 700
    assert_eq!(token_client.balance(&recipient), 700);
    // Sponsor: 2000 - 700 = 1300
    assert_eq!(token_client.balance(&sponsor), 1_300);
}

// ── M15: deposit calculation `rate * total_duration` — verify exact amount transferred

#[test]
fn m15_deposit_equals_rate_times_total_duration() {
    let env = setup_env();
    let cid = env.register(VestingDrips, ());
    let client = VestingDripsClient::new(&env, &cid);
    let sponsor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let (token, token_client) = create_token(&env, &sponsor);
    mint_to(&env, &token, &sponsor, 10_000);

    // rate=7, total=300 → deposit=2100
    client
        .create_vesting_stream(&sponsor, &recipient, &token, &7, &50, &300)
        .unwrap();

    assert_eq!(token_client.balance(&sponsor), 7_900); // 10000 - 2100
    assert_eq!(token_client.balance(&cid), 2_100);
}
