#!/usr/bin/env psql
-- seed.sql — local development fixture data
-- Usage: psql $DATABASE_URL -f scripts/seed.sql

-- Clear existing data (safe for local dev only)
TRUNCATE claims, events, schedules RESTART IDENTITY CASCADE;

-- ── Schedules ────────────────────────────────────────────────────────────────
INSERT INTO schedules
    (recipient, sponsor, token, rate_per_ledger, start_ledger, cliff_ledger, end_ledger, total_deposit, status)
VALUES
    ('GRECIPIENT1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'GSPONSOR1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     100, 1000, 18280, 190000, 18900000, 'active'),

    ('GRECIPIENT2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'GSPONSOR1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     50,  1000, 18280, 190000,  9450000, 'active'),

    ('GRECIPIENT3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'GSPONSOR2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     200, 500,  17780, 189500, 37800000, 'completed');

-- ── Events ───────────────────────────────────────────────────────────────────
INSERT INTO events
    (ledger, tx_hash, event_type, recipient, sponsor, token, amount, raw_xdr)
VALUES
    (1000, 'txhash_create_1', 'stream_created',
     'GRECIPIENT1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'GSPONSOR1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     18900000, 'AAAAAA=='),

    (1000, 'txhash_create_2', 'stream_created',
     'GRECIPIENT2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'GSPONSOR1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     9450000, 'AAAAAB=='),

    (20000, 'txhash_claim_1', 'tokens_claimed',
     'GRECIPIENT3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     NULL,
     'CTOKEN2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     5000000, 'AAAAAC==');

-- ── Claims ───────────────────────────────────────────────────────────────────
INSERT INTO claims
    (recipient, token, amount, ledger, tx_hash)
VALUES
    ('GRECIPIENT3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     'CTOKEN2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
     5000000, 20000, 'txhash_claim_1');
