apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: hashicorp-vault
  annotations:
    secrets-store-type: vault
spec:
  provider:
    vault:
      server: "https://vault.vesting.example.com:8200"
      path: "vesting"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vesting-backend"
          serviceAccountRef:
            name: vesting-backend
            namespace: vesting
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: hashicorp-vault-staging
  annotations:
    secrets-store-type: vault
spec:
  provider:
    vault:
      server: "https://vault.vesting.example.com:8200"
      path: "vesting-staging"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vesting-backend-staging"
          serviceAccountRef:
            name: vesting-backend
            namespace: vesting-staging
