{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vesting-backend.fullname" . }}
  labels:
    {{- include "vesting-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "vesting-backend.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range $envKey, $remote := .Values.externalSecret.remoteSecrets }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $remote.remoteKey }}
        {{- if $remote.property }}
        property: {{ $remote.property }}
        {{- end }}
    {{- end }}
{{- end }}
