apiVersion: v1
kind: Service
metadata:
  name: {{ include "vesting-backend.fullname" . }}
  labels:
    {{- include "vesting-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vesting-backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if .Values.canary.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vesting-backend.fullname" . }}-canary
  labels:
    {{- include "vesting-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vesting-backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
